rezzie-jsf-integration-tests/src/main/java/au/net/causal/rezzie/jsf/integrationtest/MyBean.java
package au.net.causal.rezzie.jsf.integrationtest;

import java.util.Locale;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.context.FacesContext;

import au.net.causal.rezzie.jsf.AbstractRezzieBean;

@ManagedBean
@RequestScoped
public class MyBean extends AbstractRezzieBean
{
	private String name = "John Galah";
	private String localeName;
	
	@PostConstruct
	private void init()
	{
		Locale locale = FacesContext.getCurrentInstance().getViewRoot().getLocale();
		localeName = locale.toLanguageTag();
	}
	
	public String getLocaleName()
	{
		return(localeName);
	}
	
	public String name2()
	{
		return(name);
	}
	
	public String getName()
	{
		return(name);
	}
	
	public void setName(String name)
	{
		this.name = name;
	}
	
	public String doSomething(String s)
	{
		return("Hello " + s);
	}
	
	public String doCounting(int value)
	{
		return("Count: " + (value + 1));
	}
}

rezzie-jsf-integration-tests/src/main/java/au/net/causal/rezzie/jsf/integrationtest/MyProtoBean.java
package au.net.causal.rezzie.jsf.integrationtest;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;

import au.net.causal.rezzie.jsf.AbstractRezzieBean;
import au.net.causal.rezzie.jsf.integrationtest.bundle.AppMessages;

@ManagedBean
@RequestScoped
public class MyProtoBean extends AbstractRezzieBean
{
	private final AppMessages bundle;
	
	public MyProtoBean()
	{
		bundle = getBundle(AppMessages.class);
	}
	
	public String getGreeting()
	{
		return(bundle.greeting());
	}
}

rezzie-jsf-integration-tests/src/main/java/au/net/causal/rezzie/jsf/integrationtest/MyServiceBean.java
package au.net.causal.rezzie.jsf.integrationtest;

import java.io.Serializable;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.RequestScoped;

import au.net.causal.rezzie.jsf.integrationtest.bundle.jsf.RezzieMessages;

@ManagedBean
@RequestScoped
public class MyServiceBean implements Serializable
{
	@ManagedProperty("#{msg}")
	private RezzieMessages messages;
	
	public void setMessages(RezzieMessages messages)
	{
		this.messages = messages;
	}

	public String getServiceGreeting()
	{
		return("Greetings from the service layer: " + messages.getApp().getGreeting());
	}
}

rezzie-jsf-integration-tests/src/main/webapp/param1.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
		xmlns:f="http://xmlns.jcp.org/jsf/core"      
		xmlns:h="http://xmlns.jcp.org/jsf/html">
 
    <h:head>
        <title>Test</title>
    </h:head>
    <h:body>
    	<p>Counter: #{simpleMessages.countMessage(5)}</p>
    </h:body>
</html>

rezzie-jsf-integration-tests/src/main/webapp/simple1.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
		xmlns:f="http://xmlns.jcp.org/jsf/core"      
		xmlns:h="http://xmlns.jcp.org/jsf/html">
 
    <h:head>
        <title>Test</title>
    </h:head>
    <h:body>
    	<p>Greeting: #{simpleMessages.greeting}</p>
    </h:body>
</html>

rezzie-jsf-integration-tests/src/main/webapp/t1.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
		xmlns:f="http://xmlns.jcp.org/jsf/core"      
		xmlns:h="http://xmlns.jcp.org/jsf/html">
 
    <h:head>
        <title>Hello</title>
    </h:head>
    <h:body>
    	<h3>Hello</h3>
    	<p>Hi #{myBean.name}</p>
    	<p>#{myBean.doSomething('Johnny')}</p>
    	<p>#{myBean.doCounting('5')}</p>
    	<p>Locale: #{myBean.localeName}</p>
    	<p>#{msg.app.greeting}</p>
    	<p>Counting: #{msg.app.countMessage(12)}</p>
    	
    	<p>
    	#{myServiceBean.serviceGreeting}
    	</p>
    </h:body>
</html>